- components/DatePicker/DatePicker.tsx
- hooks/useDebounce.ts
- #36 
- 달 넘어가는 스크롤 함수와, 나중에 검색기능에서도 사용하기 위해서 디바운스 훅을 구현했습니다
- 
디바운싱할 함수,  딜레이,
true: isLeading 방식 ( 이벤트가 시작할때에 함수실행)
false : 기본값, (이벤트가 끝나고 딜레이시간 이후에 함수실행) 입니다
-
-
-
-
> [feat] 디바운스 훅 작성

- components/DatePicker/DatePicker.tsx
- pages/calendar/components/Calendar/CalendarHeader/CalendarHeader.module.scss
- pages/calendar/components/Calendar/MonthlyCalendar/MonthlyCalendar.module.scss
- pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
- pages/calendar/components/CalendarSideBar/CalendarSideBar.module.scss
- pages/calendar/components/CalendarTypeSegmentedButton/CalendarTypeSegmentedButton.module.scss
-  #17 
- 월간 메인캘린더 디자인을 구현했습니다
- 캘린더에 달의 이동, 스크롤 훅을 연결했습니다
> [feat] 월간캘린더 디자인 구현

- pages/sign-in/kakao/index.page.tsx
- 에러 확인을 위해 콘솔에 에러가 찍히도록 코드를 수정했습니다.
> [fix] 에러 확인을 위한 코드 수정

- pages/sign-in/kakao/index.page.tsx
> [fix] 코드 복구

- apis/apis.ts
- components/GroupColorPicker/GroupColorPicker.module.scss
- components/GroupColorPicker/index.tsx
- components/Input/Input.module.scss
- components/Modal/CreateGroup/index.tsx
- components/Modal/ExitGroup/index.tsx
- components/Notification/BaseNotification/index.tsx
- components/Notification/CoordinationNotification/index.tsx
- components/Notification/ScheduleInfoNotification/index.tsx
- constants/queryKey.ts
- hooks/useAcceptInvite.ts
- hooks/useGetAllNotification.ts
- pages/dashboard/components/NotificationCenter/index.tsx
- pages/dashboard/index.page.tsx
- pages/group/[id]/components/ActionButton/ActionButton.module.scss
- pages/group/[id]/components/GroupForm/index.tsx
- pages/group/[id]/components/MemberList/MemberInfo/index.tsx
- pages/group/[id]/index.page.tsx
- types/type.ts
- utils/formatKoreanDateTime.ts
- #67
- 그룹 초대 수락 api 연결
추후 작업 예정
- 알림 삭제 api 생기면 추가
- 초대장 취소 api 수정되면 반영
> [feat] 그룹 초대 수락 api 연결

- components/Header/index.tsx
- pages/api/logout.page.ts
> [feat] 로그아웃 로직 추가

- components/NotificationPopup/index.tsx
- pages/dashboard/components/NotificationCenter/index.tsx
- types/type.ts
- api response 데이터명이 변경되어서, 코드를 수정하였습니다.
> [fix] api response 데이터명 변경에 따른 오류 수정

- pages/index.page.tsx
> [fix] 프로덕션 환경 변수 테스트 추가

- pages/sign-in/kakao/index.page.tsx
> [fix] 로그인 에러 확인

- pages/sign-in/index.page.tsx
- pages/sign-in/kakao/index.page.tsx
> [fix] 로그인 에러 처리, 페이지 타이틀 추가

- deploy.sh
> [fix] pm2 명령어 수정

- pages/index.page.tsx
> [fix] 배포 테스트

- package-lock.json
- package.json
- `dev-dependency`에 있던 react-lottie-player를 `dependency`로 재설치하였습니다.
> [fix] 배포 사이트에서 랜딩 페이지 안보이는 오류 수정

- appspec.yml
- deploy.sh
- pages/Home.module.scss
- pages/index.page.tsx
- styles/reset.css
- #96 
- 랜딩 페이지 Pull Page Scroll 추가
> [refactor] 랜딩 페이지 Pull Page Scroll 추가

- pages/sign-in/kakao/index.page.tsx
- access token 만료 시간이 지나도 제거되지 않는 오류가 있어, 확인용 코드를 삽입하였습니다.
> [refactor] 토큰 에러 확인용 코드 삽입

- README.md
- apis/apis.ts
- components/Notification/BaseNotification/index.tsx
- constants/queryKey.ts
- hooks/useCreateSchedule.ts
- hooks/useGetUpcomingSchedule.ts
- pages/dashboard/Dashboard.module.scss
- pages/dashboard/components/NotificationCenter/NotificationCenter.module.scss
- pages/dashboard/components/UpcomingScheduleList/UpcomingSchedule/UpcomingSchedule.module.scss
- pages/dashboard/components/UpcomingScheduleList/UpcomingSchedule/index.tsx
- pages/dashboard/components/UpcomingScheduleList/UpcomingScheduleList.module.scss
- pages/dashboard/components/UpcomingScheduleList/index.tsx
- pages/group/[id]/components/InviteForm/index.tsx
- pages/my-page/components/ProfileEditForm/index.tsx
- pages/sign-in/index.page.tsx
- types/type.ts
> [feat] 다가오는 일정 리스트 api 연결

- middleware.page.ts
- pages/sign-in/kakao/index.page.tsx
- 현재, access token의 만료시간이 지나도, 토큰이 사라지지 않는 오류가 있어, refresh token이 있을 때도, 로그인이 가능하도록 수정하였습니다.
> [fix] refresh token 있을 때도 로그인 가능하도록 수정

- README.md
> chore: 리드미 업데이트

- pages/sign-in/google/Google.module.scss
- pages/sign-in/google/index.page.tsx
- pages/sign-in/index.page.tsx
> [feat] 구글 로그인 기능 추가

- pages/api/setCookies.page.ts
- pages/sign-in/google/index.page.tsx
- pages/sign-in/kakao/index.page.tsx
- `access token` 만료시간을 5분에서 30분으로 변경하였습니다.
> [fix] access token 만료 시간 변경

- apis/apis.ts
- pages/my-page/components/ProfileEditForm/ProfileEditForm.module.scss
- pages/my-page/components/ProfileEditForm/index.tsx
> [feat] 회원 탈퇴 기능 추가

- README.md
> [chore] 리드미 업데이트

- components/Modal/Schedule/ScheduleCreate/index.tsx
- components/Modal/Schedule/ScheduleDetail/ScheduleDetailModal.module.scss
- components/Modal/Schedule/ScheduleDetail/index.tsx
- hooks/useDragSelect.ts
- pages/calendar/components/Calendar/DailyCalendar/index.tsx
- pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
- pages/calendar/components/Calendar/WeeklyCalendar/index.tsx
- #111 
- #115  
- 드래그영역 버그 수정했습니다
-
-
-
-
-
> [fix]버그수정-06.25
